### ISSUE TITLE
tools: flags for enabling features

### ISSUE THREAD

**Issue by nmoutschen** [aws-samples/aws-serverless-ecommerce-platform#85]
## Proposed change

This would add flags through CloudFormation parameters and conditions to allow enabling/disabling some resources and features based on the environment or user preferences. For example, enabling/disabling the listener SQS stack, CloudWatch dashboards, etc.

Right now, several stacks rely on an [IsProd condition](https://github.com/aws-samples/aws-serverless-ecommerce-platform/blob/master/orders/template.yaml#L50-L51) to check if prod features should be enabled.

With the proposed change, the [environments.yaml](https://github.com/aws-samples/aws-serverless-ecommerce-platform/blob/master/environments.yaml) file would add more parameters specific to these features. There would also be a new file (`features.yaml`) that would be masked in `.gitignore` where users could manually disable features that could incur costs. This file would override values from `environments.yaml`.

Right now, many features in [CloudWatch](https://aws.amazon.com/cloudwatch/pricing/) have a fixed cost per resource per month, which could create an unpleasant surprise.

However, as this relies on CloudFormation parameters, which have a limit of [60 parameters per template](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html), it's important to keep the number of feature flags low.

## Example

For example, if we have a feature to enable monitoring features and we decide to use it only for production the `environments.yaml` file would look like this:

```yaml
dev:
  parameters:
    LogLevel: DEBUG
    RetentionInDays: "7"

# ...

prod:
  parameters:
    LogLevel: INFO
    RetentionInDays: "30"
    MonitoringEnabled: false
  flags:
    can-test: false
    # This would probably be made redundant
    # is-prod: true
```

A CloudFormation template would include this (if they have monitoring features beyond the baseline):

```yaml
Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name
  #...
  MonitoringEnabled:
    Type: String
    Default: false
    Description: Enable advanced monitoring features
  #...

Conditions:
  HasMonitoring: !Equals [!Ref MonitoringEnabled, true]

#...
Resources:
  #...
  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Condition: HasMonitoring
    Properties:
      #...
```

The features file would look like this:

```yaml
features:
  MonitoringEnabled: false
```
